server:
  port: 8762 #the default port used for zuul service
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5

spring:
  cloud:
    gateway:
      routes:
      - id: orderService
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/orderService/**
